### ISSUE TITLE
Compilation on CentOS 7 fails: error: expected ')' before 'PRId64'

### ISSUE THREAD

**Issue by paraenggu** [Opendigitalradio/etisnoop#16]
Compiling etisnoop on CentOS 7 fails with the following error:

```
fig0_21.cpp:193:56: error: expected ')' before 'PRId64'
                 sprintf(tmpbuf, ", database key=0x%09" PRId64, key);
```

After switching from `#include <inttypes.h>` to `#include <cinttypes>` etisnoop compiles correctly:

``` bash
sed -i -e 's/^\(#include\) <inttypes.h>/\1 <cinttypes>/' \
    etisnoop.cpp utils.hpp wavfile.h
```

**Comment by mpbraendli** [comment]
Fixed in 8823ffb8e0cd34615f44e5d241030c57a7465153
I find it strange that this makes a difference, but I won't investigate. Thanks for the report!
