### ISSUE TITLE
Request for release tag

### ISSUE THREAD

**Issue by paraenggu** [Opendigitalradio/etisnoop#17]
We're packaging [etisnoop on CentOS 7](https://github.com/radiorabe/centos-rpm-etisnoop). It would be helpful if you could create a release tag.

Many thanks!

**Comment by mpbraendli** [comment]
Created a version tag!

**Comment by mpbraendli** [comment]
Warning: I've moved to autotools and have created v1.1.0 already. Now etisnoop knows what version it is, and make dist also creates nice tarballs.

**Comment by mpbraendli** [comment]
Version 1.1.0 released.

**Comment by paraenggu** [comment]
Thanks a lot! Just added a 1.1.0 spec with radiorabe/centos-rpm-etisnoop@16f06b695f201e97444619f7d9fcab7f0cc52e4f
