### ISSUE TITLE
Cannot make newer etisnoop versions

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/etisnoop#19]
When I try to make it under Ubuntu 16.04 64bit, I get the following (German) error

> ...
  CC       src/wavfile.o
  CC       src/fec/decode_rs_char.o
  CC       src/fec/encode_rs_char.o
  CC       src/fec/init_rs_char.o
  CXXLD    etisnoop
/usr/bin/ld: cannot find -lboost_regex
collect2: error: ld returned 1 exit status
Makefile:575: die Regel für Ziel „etisnoop“ scheiterte
make[1]: *** [etisnoop] Fehler 1
make[1]: Verzeichnis „/home/andreas/etisnoop“ wird verlassen
Makefile:390: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

An older version I have downloaded in October works.

**Comment by mpbraendli** [comment]
Hello, the newest versions require boost to be installed.
Did you run bootstrap after you did git pull?

**Comment by andimik** [comment]
Boost was to be installed, but I've installed it again through

`sudo apt-get install libboost-all-dev
`

Yes, now I could make etisnoop. 

Thanks for the hint.

**Comment by andimik** [comment]
Maybe you could mention in the readme that under Ubuntu boost has to be installed with that command?

And I had to add this package:

`sudo apt-get install dh-autoreconf`
