### ISSUE TITLE
Wrong EEP value in FIG

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/etisnoop#20]
Seems you have always to add 1 in order to get the correct EEP protection level for FIG (only there!).

There is no EEP 0-A and no EEP-0-B. In my example below I wrote this file:

[test_protlev.txt](https://github.com/Opendigitalradio/etisnoop/files/1226404/test_protlev.txt)

```
Subch 0x1
start_addr 0
long
**EEP 0-A**
subch size 144
```

```
Subch 0x5
start_addr 360
long
**EEP 0-B**
subch size 81
```

And the CUs are wrong, for 96 kBit
1A is 144 CU, 2A is 96, 3A is 72, 4A is 48, and so on.

```
TPL  - Sub-channel Type and Protection Level [0x20 - Equal Error Protection. 1-A, 1/4, 16 CUs] 
TPL  - Sub-channel Type and Protection Level [0x21 - Equal Error Protection. 2-A, 3/8, 8 CUs] 
TPL  - Sub-channel Type and Protection Level [0x22 - Equal Error Protection. 3-A, 1/2, 6 CUs] 
TPL  - Sub-channel Type and Protection Level [0x23 - Equal Error Protection. 4-A, 3/4, 4 CUs] 
TPL  - Sub-channel Type and Protection Level [0x24 - Equal Error Protection. 1-B, 4/9, 27 CUs] 
TPL  - Sub-channel Type and Protection Level [0x25 - Equal Error Protection. 2-B, 4/7, 21 CUs] 
TPL  - Sub-channel Type and Protection Level [0x26 - Equal Error Protection. 3-B, 4/6, 18 CUs] 
TPL  - Sub-channel Type and Protection Level [0x27 - Equal Error Protection. 4-B, 4/5, 15 CUs] 
```

**Comment by mpbraendli** [comment]
Thanks, fixed!

**Comment by andimik** [comment]
Are you sure?

Because the word "protection" (lower case) is not printed out, not even with `-v -f`.

So I fear you've modified the wrong file.

I guess it should be `fig0_1.cpp`, line 86 and 89.

**Comment by mpbraendli** [comment]
Yeah, I did that a bit too quickly and fixed the printout for the statistics file only. Now it should be ok.

**Comment by andimik** [comment]
Ein Grüezi in die Schweiz, 

Statistics File? Is this a new feature? How to get that? Not found a description on http://wiki.opendigitalradio.org/Etisnoop

Meaning the wiki is outdated ;-)

**Comment by mpbraendli** [comment]
Yes, nor have I written anything to the README :-)
It's the -s option, to be combined with https://github.com/mpbraendli/mmbtools-aux/tree/master/etisnoop-stat-server
