### ISSUE TITLE
Special chars not supported?

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/etisnoop#21]
Remark: All outputs below are from `-s file.txt`

If you extract eti from the rawfiles from https://sdr.kt.agh.edu.pl/sdrdab-decoder/download.html (for example use eti-stuff from Jan, https://github.com/JvanKatwijk/eti-stuff ), you will see that special characters are not supported:

```
    - service_id: 0x3222
      subchannel_id: 0x2
      label: PR Dwjka       
      shortlabel: Dwjka
```
instead of Dwójka.

Or in Vienna,

```
    - service_id: 0xad0b
      subchannel_id: 0xd
      label: ARB×-Radio      
      shortlabel: ARB×
```

instead of ARBÖ.

BTW: the normal -v output does **not** mention ARBÖ-Radio at all

```
$ etisnoop -v < ~/wien_16072017.eti | grep Rad
					Label: "NOW Radio       "
					Label: "MEGA Radio      "
					Label: "Radio U1 Tirol  "
```

In Nitra, Slovakia, the mux is in unicode (said user basicmaster)

![grafik](https://user-images.githubusercontent.com/24510556/29384417-491d8e5c-82d4-11e7-90b1-b053ee6e6295.png)
`FICDecoder: SId 0x5005: programme service label 'Rádio Litera'` (output from dablin)

but etisnoop writes wrong data (please note short label Ro Liter instead of R Litera)

```
    - service_id: 0x5005
      subchannel_id: 0x1
      label: RÃ¡dio Litera   
      shortlabel: Ro Liter
```

**Comment by mpbraendli** [comment]
Your observation is correct, etisnoop does not decode the labels, it just prints them as-is. Thanks for notifying.
I don't think I'll be able to work in this soon, so I'll leave the issue open. Patches are always welcome!
Maybe we could easily re-use the decoder @basicmaster implemented in dablin.

**Comment by BobinJ** [comment]
can you please explain the procedures of reading data from an eti file

**Comment by mpbraendli** [comment]
This should now be fixed. Also, FIG2 labels are now decoded.
