### ISSUE TITLE
Missing fig0_7.cpp

### ISSUE THREAD

**Issue by flanti** [Opendigitalradio/etisnoop#27]
Missing src/fig0_7.cpp

I have used [this script](https://github.com/mpbraendli/mmbtools-aux/blob/master/installer/debian.sh) to install.

It gives error:
```
make[1]: *** No rule to make target 'src/fig0_7.cpp', needed by 'src/fig0_7.o'. Stop
make[1]:  Leaving directory '/home/user/mmbtools/dab/etisnoop'
make: *** [Makefile:418: all] Error 2
```

Thank You!

**Comment by mpbraendli** [comment]
Uh, I forgot, sorry.
Thanks for the notice!

**Comment by fauust** [comment]
@mpbraendli why not adding some CI to those project?
I believe having a github action that automatically build those is not difficult to implement... :-)

**Comment by mpbraendli** [comment]
Yes sure, it's one of these "not difficult but takes some time" things. :-)
