### ISSUE TITLE
Same special character displayed in 4 variants

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/etisnoop#28]
Attached file from Austria includes a service with German special character ö, but it seems that etisnoop uses several different character tables to display it ...

# console 
- in the long label ö
- in the short lable �

# yaml file

- in the long lable Ã¶ 
- in the short lable   (maybe shown not correct here on github)

[ors_8a_2020-06-14_1052.zip](https://github.com/Opendigitalradio/etisnoop/files/5539339/ors_8a_2020-06-14_1052.zip)

```
$ LC_ALL=C etisnoop -n 10000 -i ./ors_8a_2020-06-14_1052.eti | LC_ALL=C grep "live" -B 10 | sort | uniq
Identified ETI type RAW
ERRORS: Not yet in DB
ERRORS: Not yet in DB
ERRORS: Not yet in DB
Error: FCT not contiguous
ERRORS: Not yet in DB
ERRORS: Not yet in DB
Incomplete frame in ETI file!
ETI file read error
    -
--
      Charset: 0
   CRC: OK
     Decoding:
   FIB: 1
   FIB: 2
     FIG: 1/1
   FIGs:
      Label: "jö.live         "
     Length: 21
     OE: 0
      Service ID: 0xAD56
      Short label: j�.live
      Short label mask: 0xFE00
```

`$ LC_ALL=C etisnoop -n 10000 -i ./ors_8a_2020-06-14_1052.eti -s /tmp/ors_8a_2020-06-14_1052.yaml` produces this yaml-file:
[ors_8a_2020-06-14_1052.yaml.zip](https://github.com/Opendigitalradio/etisnoop/files/5539363/ors_8a_2020-06-14_1052.yaml.zip)
where you can see
```
      label: jÃ¶.live         
      shortlabel: j.live
```

**Comment by mpbraendli** [comment]
Commit 4f7218f should fix this, so that short labels are also written encoded as UTF-8.

**Comment by andimik** [comment]
yes, confirmed, thanks!
