### ISSUE TITLE
Line "DG flag: data groups ..."  contains an extra newline char, messing up yaml

### ISSUE THREAD

**Issue by MichalLeonBorsuk** [Opendigitalradio/etisnoop#32]
Hi, 

I've come across a weird issue: the line 'DG flag: 0 data groups are [not] used to transport the service component' always has a newline character after 'DG flag: 0', thus producing invalid yaml. 

This is what I get: 

>        DG flag: 0
>        data groups are used to transport the service component
>        DSCTy: 60 Multimedia Object Transfer (MOT)

This is what yaml expects: 

>        DG flag: 0 data groups are used to transport the service component       
>        DSCTy: 60 Multimedia Object Transfer (MOT)

This little script helps, but it's not really a solution; 

```
#!/usr/bin/env bash

cp $1 $1--backup

sed -i  's/data groups are used to transport the service component//' $1
sed -i 's/DG flag: 0/DG flag: 0 data groups are used to transport the service component/' $1
```

PS I'm sorry that I can't currently repair this myself, gdb is crashing on me.

**Comment by mpbraendli** [comment]
Ah yes, thanks for mentioning this. I think the best is to simply remove the text message. I've done this in 8dd702b
