### ISSUE TITLE
missing stdint.h in ensembledatabase.hpp

### ISSUE THREAD

**Issue by andimik** [Opendigitalradio/etisnoop#33]
I get an error when compiling under Ubuntu 23.10 with 9734cb9156ff.

[compile_error.txt](https://github.com/Opendigitalradio/etisnoop/files/13418089/compile_error.txt)

```
make[1]: *** [Makefile:695: src/ensembledatabase.o] Error 1
make[1]: Leaving directory '/home/andreas/apps/etisnoop'
make: *** [Makefile:421: all] Error 2
```

Seems in `src/ensembledatabase.hpp`

```
#include <stdint.h>
```
was missing. Only then I could compile.

**Comment by mpbraendli** [comment]
Thanks, I've added the missing include!
